# JWT
mp.jwt.verify.issuer=vovandiya
mp.jwt.verify.publickey.location=rsa/publicKey.pem
smallrye.jwt.sign.key.location=rsa/privateKey.pem

# Dev Services
quarkus.devservices.enabled=false

# Datasource
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=user
quarkus.datasource.password=password
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/sflottery
quarkus.datasource.devservices.enabled=false

# Hibernate
quarkus.hibernate-orm.schema-management.strategy=update

# Test profile
%test.quarkus.datasource.db-kind=postgresql
%test.quarkus.datasource.devservices.enabled=true
%test.quarkus.datasource.devservices.db-name=sflottery_test

# Lottery Daily Prop

lottery.daily-draw.cron=0 0 0 * * ?
lottery.daily-run.cron=0 5 0 * * ?
lottery.daily.format=1-90:5
lottery.daily.prise-pool=100000
lottery.daily.instantaneous=true